name: StaffChat
version: '${project.version}'
main: nathan.staffchat.StaffChat
author: "Elephant_1214"
description: A basic staff chat plugin for my server, Zirkon Network
commands:
  staffchat:
    description: Toggles staff chat or sends a message in staff chat if you include arguments
    aliases:
      - sc
    permission: sc.use
    usage: /<command> <args>
  reloadstaffchat:
    description: Reloads the plugin to get the latest config changes
    aliases:
      - reloadsc
      - rsc
    permission: sc.manage
    usage: /<command>
permissions:
  sc.use:
    description: Allows usage of /staffchat for toggling and sending messages
    default: op
  sc.view:
    description: Makes messages sent in staff chat visible to the player
    default: op
  sc.manage:
    description: Allows the player to reload the plugin
    default: op

